name: Build and Release Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --name "FF14_TC_Launcher" src/main.py

    - name: Compress Release Archive
      run: |
        powershell Compress-Archive -Path dist/FF14_TC_Launcher.exe -DestinationPath dist/FF14_TC_Launcher.zip

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/FF14_TC_Launcher.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
